"""empty message

Revision ID: c7d3e78515ad
Revises: dce810701bc6
Create Date: 2021-05-02 21:35:02.855197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d3e78515ad'
down_revision = 'dce810701bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_email_key', 'customer', type_='unique')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_unique_constraint('customer_email_key', 'customer', ['email'])
    # ### end Alembic commands ###
